version: '2'

services:
  app:
    image: 'dashmployee:latest'
    build:
      context: .
    container_name: app
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db    
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/university
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
          
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=university
    expose:
      - "5432:5432"